package org.web4thejob.studio;

/**
 * Created by e36132 on 14/5/2014.
 */
public enum MessageEnum {
    COMPONENT_ADDED, COMPONENT_SELECTED, COMMAND_SELECTED,
    COMPONENT_DETACHED, DESCRIPTION_CHANGED,
    EVALUATE_XML, XML_EVAL_FAILED, XML_EVAL_SUCCEEDED,
    EVALUATE_ZUL, ZUL_EVAL_FAILED, ZUL_EVAL_SUCCEEDED,
    CODE_CHANGED, SET_BOOKMARK, RESET, RESTORE_BOOKMARK

}
