package org.web4thejob.studio;

/**
 * Created by e36132 on 14/5/2014.
 */
public enum MessageEnum {
    COMPONENT_ADDED, COMPONENT_SELECTED, COMMAND_SELECTED,
    COMPONENT_DETACHED, DESCRIPTION_CHANGED, CODE_EVAL_FAILED,
    CODE_EVAL_SUCCEDED, CODE_CHANGED, EVALUATE_CODE,
    SET_BOOKMARK, RESET, RESTORE_BOOKMARK

}
