package org.web4thejob.studio.message;

/**
 * Created by e36132 on 14/5/2014.
 */
public enum MessageEnum {
    COMPONENT_SELECTED, COMPONENT_ADDED, COMPONENT_DETACHED,
    EVALUATE_XML, XML_EVAL_FAILED, XML_EVAL_SUCCEEDED,
    EVALUATE_ZUL, ZUL_EVAL_FAILED, ZUL_EVAL_SUCCEEDED,
    CODE_CHANGED, ATTRIBUTE_CHANGED,
    SET_BOOKMARK, RESET, RESTORE_BOOKMARK, ZK_PAGE_VISITED, NON_ZK_PAGE_VISITED,
    DESIGNER_ACTIVATED, OUTLINE_ACTIVATED, CODE_ACTIVATED, ZSCRIPT_ADDED

}
